# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(217, 236)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.showStructureButton = QtWidgets.QPushButton(self.centralwidget)
        self.showStructureButton.setObjectName("showStructureButton")
        self.verticalLayout.addWidget(self.showStructureButton)
        self.showBoardButton = QtWidgets.QPushButton(self.centralwidget)
        self.showBoardButton.setObjectName("showBoardButton")
        self.verticalLayout.addWidget(self.showBoardButton)
        self.testButton = QtWidgets.QPushButton(self.centralwidget)
        self.testButton.setObjectName("testButton")
        self.verticalLayout.addWidget(self.testButton)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.erasingButton = QtWidgets.QPushButton(self.centralwidget)
        self.erasingButton.setObjectName("erasingButton")
        self.verticalLayout.addWidget(self.erasingButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.showStructureButton.setText(_translate("MainWindow", "1. Show Model Structure"))
        self.showBoardButton.setText(_translate("MainWindow", "2. Show TensorBoard"))
        self.testButton.setText(_translate("MainWindow", "3. Test"))
        self.erasingButton.setText(_translate("MainWindow", "4. Random-Erasing"))
